---
title: Remotely control your buggy
hero_image: images/banner.png
description: Create a remote control for your Raspberry Pi buggy
original_url:
theme: red
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-2, manufacture-1, community-0
interests: robotics
technologies: electronic-components, python
hardware: electronic-components
software: python
site_areas: projects
version: 4
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: An Android remote control
- title: An AIY Projects Voice Kit remote control
  completion: internal
- title: A home-brew remote control
